get http://localhost:3001/blog/notes/
###
delete http://localhost:3005/api/notes/4
###
post http://localhost:3001/blog/notes
Content-Type: application/json

{
    "content": "What are you doing?",
    "important": false
}
###
post http://localhost:3001/blog/users
Content-Type: application/json

{
    "username": "TheBigFucker",
    "name": "stacvirus",
    "password": "areyoudeath??"
}